version: 0.2

phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
  build:
    commands:
    - echo building the code-repo-demo
    - mvn install
    - ls -larth 
artifacts:
  files:
  - target/*.jar
 # - scripts/*.sh
 # - appspec.yml
  discard-paths: yes

#cache:
 # paths:
#  - '/root/.m2/**/*'
